# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ajay\Desktop\chart_temp.ui'
#
# Created: Sun Aug 23 17:23:19 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from PySide.QtWebKit import QWebView

class Ui_Dialog(QtGui.QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1020, 624)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/stockmarket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton = QtGui.QToolButton(Dialog)
        self.toolButton.setMinimumSize(QtCore.QSize(200, 100))
        self.toolButton.setAutoFillBackground(False)
        self.toolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(200, 100))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(100, 100))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filter_selector = QtGui.QComboBox(self.groupBox)
        self.filter_selector.setObjectName("filter_selector")
        self.verticalLayout_2.addWidget(self.filter_selector)
        self.company_selector = QtGui.QComboBox(self.groupBox)
        self.company_selector.setObjectName("company_selector")
        self.verticalLayout_2.addWidget(self.company_selector)
        self.viewer = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.viewer.setFont(font)
        self.viewer.setObjectName("viewer")
        self.verticalLayout_2.addWidget(self.viewer)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.company_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.company_label.setFont(font)
        self.company_label.setObjectName("company_label")
        self.horizontalLayout_5.addWidget(self.company_label)
        self.company_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.company_val.setFont(font)
        self.company_val.setText("")
        self.company_val.setObjectName("company_val")
        self.horizontalLayout_5.addWidget(self.company_val)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.open_price_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.open_price_label.setFont(font)
        self.open_price_label.setObjectName("open_price_label")
        self.horizontalLayout_7.addWidget(self.open_price_label)
        self.open_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.open_val.setFont(font)
        self.open_val.setText("")
        self.open_val.setObjectName("open_val")
        self.horizontalLayout_7.addWidget(self.open_val)
        self.dummy1 = QtGui.QLabel(Dialog)
        self.dummy1.setText("")
        self.dummy1.setObjectName("dummy1")
        self.horizontalLayout_7.addWidget(self.dummy1)
        self.dummy2 = QtGui.QLabel(Dialog)
        self.dummy2.setText("")
        self.dummy2.setObjectName("dummy2")
        self.horizontalLayout_7.addWidget(self.dummy2)
        self.dummy3 = QtGui.QLabel(Dialog)
        self.dummy3.setText("")
        self.dummy3.setObjectName("dummy3")
        self.horizontalLayout_7.addWidget(self.dummy3)
        self.dummy4 = QtGui.QLabel(Dialog)
        self.dummy4.setText("")
        self.dummy4.setObjectName("dummy4")
        self.horizontalLayout_7.addWidget(self.dummy4)
        self.dummy5 = QtGui.QLabel(Dialog)
        self.dummy5.setText("")
        self.dummy5.setObjectName("dummy5")
        self.horizontalLayout_7.addWidget(self.dummy5)
        self.dummy6 = QtGui.QLabel(Dialog)
        self.dummy6.setText("")
        self.dummy6.setObjectName("dummy6")
        self.horizontalLayout_7.addWidget(self.dummy6)
        self.dummy7 = QtGui.QLabel(Dialog)
        self.dummy7.setText("")
        self.dummy7.setObjectName("dummy7")
        self.horizontalLayout_7.addWidget(self.dummy7)
        self.dummy8 = QtGui.QLabel(Dialog)
        self.dummy8.setText("")
        self.dummy8.setObjectName("dummy8")
        self.horizontalLayout_7.addWidget(self.dummy8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.high_val_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.high_val_label.setFont(font)
        self.high_val_label.setObjectName("high_val_label")
        self.horizontalLayout_8.addWidget(self.high_val_label)
        self.high_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.high_val.setFont(font)
        self.high_val.setText("")
        self.high_val.setObjectName("high_val")
        self.horizontalLayout_8.addWidget(self.high_val)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_8.addWidget(self.line_4)
        self.futuro_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.futuro_label.setFont(font)
        self.futuro_label.setObjectName("futuro_label")
        self.horizontalLayout_8.addWidget(self.futuro_label)
        self.futuro_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.futuro_val.setFont(font)
        self.futuro_val.setText("")
        self.futuro_val.setObjectName("futuro_val")
        self.horizontalLayout_8.addWidget(self.futuro_val)
        self.line_5 = QtGui.QFrame(Dialog)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_8.addWidget(self.line_5)
        self.short_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.short_label.setFont(font)
        self.short_label.setObjectName("short_label")
        self.horizontalLayout_8.addWidget(self.short_label)
        self.short_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.short_val.setFont(font)
        self.short_val.setText("")
        self.short_val.setObjectName("short_val")
        self.horizontalLayout_8.addWidget(self.short_val)
        self.line_6 = QtGui.QFrame(Dialog)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_8.addWidget(self.line_6)
        self.pivot_change_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.pivot_change_label.setFont(font)
        self.pivot_change_label.setObjectName("pivot_change_label")
        self.horizontalLayout_8.addWidget(self.pivot_change_label)
        self.pivot_change_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.pivot_change_val.setFont(font)
        self.pivot_change_val.setText("")
        self.pivot_change_val.setObjectName("pivot_change_val")
        self.horizontalLayout_8.addWidget(self.pivot_change_val)
        self.line_7 = QtGui.QFrame(Dialog)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_8.addWidget(self.line_7)
        self.dummy9 = QtGui.QLabel(Dialog)
        self.dummy9.setText("")
        self.dummy9.setObjectName("dummy9")
        self.horizontalLayout_8.addWidget(self.dummy9)
        self.dummy10 = QtGui.QLabel(Dialog)
        self.dummy10.setText("")
        self.dummy10.setObjectName("dummy10")
        self.horizontalLayout_8.addWidget(self.dummy10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.low_price_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.low_price_label.setFont(font)
        self.low_price_label.setObjectName("low_price_label")
        self.horizontalLayout_3.addWidget(self.low_price_label)
        self.low_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.low_val.setFont(font)
        self.low_val.setText("")
        self.low_val.setObjectName("low_val")
        self.horizontalLayout_3.addWidget(self.low_val)
        self.line_8 = QtGui.QFrame(Dialog)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_3.addWidget(self.line_8)
        self.certus_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.certus_label.setFont(font)
        self.certus_label.setObjectName("certus_label")
        self.horizontalLayout_3.addWidget(self.certus_label)
        self.certus_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.certus_val.setFont(font)
        self.certus_val.setText("")
        self.certus_val.setObjectName("certus_val")
        self.horizontalLayout_3.addWidget(self.certus_val)
        self.line_9 = QtGui.QFrame(Dialog)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_3.addWidget(self.line_9)
        self.mid_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.mid_label.setFont(font)
        self.mid_label.setObjectName("mid_label")
        self.horizontalLayout_3.addWidget(self.mid_label)
        self.mid_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.mid_val.setFont(font)
        self.mid_val.setText("")
        self.mid_val.setObjectName("mid_val")
        self.horizontalLayout_3.addWidget(self.mid_val)
        self.line_10 = QtGui.QFrame(Dialog)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_3.addWidget(self.line_10)
        self.momentum_change_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.momentum_change_label.setFont(font)
        self.momentum_change_label.setObjectName("momentum_change_label")
        self.horizontalLayout_3.addWidget(self.momentum_change_label)
        self.momentum_change_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.momentum_change_val.setFont(font)
        self.momentum_change_val.setText("")
        self.momentum_change_val.setObjectName("momentum_change_val")
        self.horizontalLayout_3.addWidget(self.momentum_change_val)
        self.line_11 = QtGui.QFrame(Dialog)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_3.addWidget(self.line_11)
        self.macd_change_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.macd_change_label.setFont(font)
        self.macd_change_label.setObjectName("macd_change_label")
        self.horizontalLayout_3.addWidget(self.macd_change_label)
        self.macd_change_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.macd_change_val.setFont(font)
        self.macd_change_val.setText("")
        self.macd_change_val.setObjectName("macd_change_val")
        self.horizontalLayout_3.addWidget(self.macd_change_val)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.close_price_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.close_price_label.setFont(font)
        self.close_price_label.setObjectName("close_price_label")
        self.horizontalLayout_6.addWidget(self.close_price_label)
        self.close_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.close_val.setFont(font)
        self.close_val.setText("")
        self.close_val.setObjectName("close_val")
        self.horizontalLayout_6.addWidget(self.close_val)
        self.line_12 = QtGui.QFrame(Dialog)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_6.addWidget(self.line_12)
        self.velox_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.velox_label.setFont(font)
        self.velox_label.setObjectName("velox_label")
        self.horizontalLayout_6.addWidget(self.velox_label)
        self.velox_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.velox_val.setFont(font)
        self.velox_val.setText("")
        self.velox_val.setObjectName("velox_val")
        self.horizontalLayout_6.addWidget(self.velox_val)
        self.line_13 = QtGui.QFrame(Dialog)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_6.addWidget(self.line_13)
        self.long_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.long_label.setFont(font)
        self.long_label.setObjectName("long_label")
        self.horizontalLayout_6.addWidget(self.long_label)
        self.long_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.long_val.setFont(font)
        self.long_val.setText("")
        self.long_val.setObjectName("long_val")
        self.horizontalLayout_6.addWidget(self.long_val)
        self.line_14 = QtGui.QFrame(Dialog)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_6.addWidget(self.line_14)
        self.stochastic_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.stochastic_label.setFont(font)
        self.stochastic_label.setObjectName("stochastic_label")
        self.horizontalLayout_6.addWidget(self.stochastic_label)
        self.stochastic_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.stochastic_val.setFont(font)
        self.stochastic_val.setText("")
        self.stochastic_val.setObjectName("stochastic_val")
        self.horizontalLayout_6.addWidget(self.stochastic_val)
        self.line_15 = QtGui.QFrame(Dialog)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.horizontalLayout_6.addWidget(self.line_15)
        self.short_term_change_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.short_term_change_label.setFont(font)
        self.short_term_change_label.setObjectName("short_term_change_label")
        self.horizontalLayout_6.addWidget(self.short_term_change_label)
        self.short_term_change_val = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.short_term_change_val.setFont(font)
        self.short_term_change_val.setText("")
        self.short_term_change_val.setObjectName("short_term_change_val")
        self.horizontalLayout_6.addWidget(self.short_term_change_val)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.graph_tab = QtGui.QWidget()
        self.graph_tab.setObjectName("graph_tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.graph_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.web_view = QWebView(self.graph_tab)
        self.web_view.setObjectName("web_view")
        self.gridLayout_2.addWidget(self.web_view,0,0,1,1)
        #self.graphicsView = QtGui.(self.graph_tab)
        #self.graphicsView.setObjectName("graphicsView")
        #self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.graph_tab, "")
        self.table_tab = QtGui.QWidget()
        self.table_tab.setObjectName("table_tab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.table_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.table_data = QtGui.QTableWidget(self.table_tab)
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(0)
        self.table_data.setRowCount(0)
        self.verticalLayout_5.addWidget(self.table_data)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.table_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "NexusChart", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "NexusFilter", None, QtGui.QApplication.UnicodeUTF8))
        self.viewer.setText(QtGui.QApplication.translate("Dialog", "VIEW", None, QtGui.QApplication.UnicodeUTF8))
        self.company_label.setText(QtGui.QApplication.translate("Dialog", "COMPANY :", None, QtGui.QApplication.UnicodeUTF8))
        self.open_price_label.setText(QtGui.QApplication.translate("Dialog", "OPEN :", None, QtGui.QApplication.UnicodeUTF8))
        self.high_val_label.setText(QtGui.QApplication.translate("Dialog", "HIGH :", None, QtGui.QApplication.UnicodeUTF8))
        self.futuro_label.setText(QtGui.QApplication.translate("Dialog", "FUTURO :", None, QtGui.QApplication.UnicodeUTF8))
        self.short_label.setText(QtGui.QApplication.translate("Dialog", "SHORT :", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_change_label.setText(QtGui.QApplication.translate("Dialog", "PIVOT % :", None, QtGui.QApplication.UnicodeUTF8))
        self.low_price_label.setText(QtGui.QApplication.translate("Dialog", "LOW :", None, QtGui.QApplication.UnicodeUTF8))
        self.certus_label.setText(QtGui.QApplication.translate("Dialog", "CERTUS :", None, QtGui.QApplication.UnicodeUTF8))
        self.mid_label.setText(QtGui.QApplication.translate("Dialog", "MID :", None, QtGui.QApplication.UnicodeUTF8))
        self.momentum_change_label.setText(QtGui.QApplication.translate("Dialog", "MNTM % :", None, QtGui.QApplication.UnicodeUTF8))
        self.macd_change_label.setText(QtGui.QApplication.translate("Dialog", "MACD % :", None, QtGui.QApplication.UnicodeUTF8))
        self.close_price_label.setText(QtGui.QApplication.translate("Dialog", "CLOSE :", None, QtGui.QApplication.UnicodeUTF8))
        self.velox_label.setText(QtGui.QApplication.translate("Dialog", "VELOX :", None, QtGui.QApplication.UnicodeUTF8))
        self.long_label.setText(QtGui.QApplication.translate("Dialog", "LONG :", None, QtGui.QApplication.UnicodeUTF8))
        self.stochastic_label.setText(QtGui.QApplication.translate("Dialog", "STOCH :", None, QtGui.QApplication.UnicodeUTF8))
        self.short_term_change_label.setText(QtGui.QApplication.translate("Dialog", "SHRT % :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graph_tab), QtGui.QApplication.translate("Dialog", "Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.table_tab), QtGui.QApplication.translate("Dialog", "Data", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
