# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ajay\PycharmProjects\NexusMont\ui_files\home_ui.ui'
#
# Created: Sat May 23 20:01:56 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/stockmarket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/images/background.png);")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 120, 671, 301))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_button = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.import_button.setMinimumSize(QtCore.QSize(100, 100))
        self.import_button.setMaximumSize(QtCore.QSize(100, 100))
        self.import_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_button.setIcon(icon1)
        self.import_button.setIconSize(QtCore.QSize(100, 100))
        self.import_button.setAutoRaise(True)
        self.import_button.setObjectName("import_button")
        self.horizontalLayout.addWidget(self.import_button)
        self.chart_button = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.chart_button.setMinimumSize(QtCore.QSize(100, 100))
        self.chart_button.setMaximumSize(QtCore.QSize(100, 100))
        self.chart_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chart_button.setIcon(icon2)
        self.chart_button.setIconSize(QtCore.QSize(100, 100))
        self.chart_button.setAutoRaise(True)
        self.chart_button.setObjectName("chart_button")
        self.horizontalLayout.addWidget(self.chart_button)
        self.setting_button = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.setting_button.setMinimumSize(QtCore.QSize(100, 100))
        self.setting_button.setMaximumSize(QtCore.QSize(100, 100))
        self.setting_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_button.setIcon(icon3)
        self.setting_button.setIconSize(QtCore.QSize(100, 100))
        self.setting_button.setAutoRaise(True)
        self.setting_button.setObjectName("setting_button")
        self.horizontalLayout.addWidget(self.setting_button)
        self.close_button = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.close_button.setMinimumSize(QtCore.QSize(100, 100))
        self.close_button.setMaximumSize(QtCore.QSize(100, 100))
        self.close_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon4)
        self.close_button.setIconSize(QtCore.QSize(100, 100))
        self.close_button.setAutoRaise(True)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.main_line_hor = QtGui.QFrame(self.centralwidget)
        self.main_line_hor.setGeometry(QtCore.QRect(7, 100, 881, 20))
        self.main_line_hor.setFrameShape(QtGui.QFrame.HLine)
        self.main_line_hor.setFrameShadow(QtGui.QFrame.Sunken)
        self.main_line_hor.setObjectName("main_line_hor")
        self.logo_button = QtGui.QToolButton(self.centralwidget)
        self.logo_button.setGeometry(QtCore.QRect(0, 0, 200, 100))
        self.logo_button.setMinimumSize(QtCore.QSize(200, 100))
        self.logo_button.setMaximumSize(QtCore.QSize(200, 100))
        self.logo_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo_button.setIcon(icon5)
        self.logo_button.setIconSize(QtCore.QSize(200, 100))
        self.logo_button.setAutoRaise(True)
        self.logo_button.setObjectName("logo_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NexusMont", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
